name: Update HMD Open Source Versions

on:
  schedule:
    - cron: '0 1 * * 1,4'
  workflow_dispatch:

jobs:
  update-versions:
    runs-on: ubuntu-latest
    
    # ADD THIS BLOCK
    # This grants the GITHUB_TOKEN write permissions for this job
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python scraper
        run: python hmd_scraper.py

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated update of HMD open source versions"
          file_pattern: "hmd_versions.json hmd_versions.sh"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
