name: Update HMD Open Source Versions

# Controls when the action will run
on:
  # Schedule to run twice a week: every Monday and Thursday at 01:00 UTC
  schedule:
    - cron: '0 1 * * 1,4'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-versions:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository code
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run the scraper script to generate the version files
      - name: Run Python scraper
        run: python hmd_scraper.py

      # 5. Commit the changes back to the repository if any files were changed
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated update of HMD open source versions"
          file_pattern: "hmd_versions.json hmd_versions.sh"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
